version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: tipstoken_user
      POSTGRES_PASSWORD: 9j[r%(Y8
      POSTGRES_DB: tipstoken__db_1a2b3c
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
